apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-com-cert
  namespace: default
spec:
  secretName: example-com-tls
  commonName: your-domain.com
  dnsNames:
    - your-domain.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

