apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-com-cert
  namespace: default
spec:
  secretName: example-com-tls
  commonName: manoj.opsguru.online
  dnsNames:
    - manoj.opsguru.online
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

